CREATE TABLE StudySets (
    StudySetID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    PdfData VARBINARY(MAX) NOT NULL,
    Progress INT NOT NULL DEFAULT 0,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);